/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "stdafx.h"
#ifndef _Included_Pmem_H
#define _Included_Pmem_H

typedef struct PowerSaveProp
{
    /*地址的偏移*/
    int nAddrOffset;
		/*写入数据的长度*/
		int nAddrLen;  
    /*地址buf*/
    vector<uchar > WriteBuff;

}POWER_SAVE_PROP;

POWER_SAVE_PROP getPmemParamFromJni(JNIEnv *env, jobject joPmemParam,int	flag);
void setPmemParamToJni(JNIEnv *env, jobject joSend, POWER_SAVE_PROP mPmemProp/*,vector<uchar > tmpList,jbyte *buf*/);

#ifdef __cplusplus
extern "C" {
#endif
 		JNIEXPORT void JNICALL Java_com_android_Samkoonhmi_pmem_PowerSave_open
        (JNIEnv *env, jobject thiz);

    JNIEXPORT void JNICALL Java_com_android_Samkoonhmi_pmem_PowerSave_close
        (JNIEnv *env, jobject thiz);
  
 	JNIEXPORT void JNICALL Java_com_android_Samkoonhmi_pmem_PowerSave_clearmem
        (JNIEnv *env, jobject thiz,jint index);
 
 		JNIEXPORT void JNICALL Java_com_android_Samkoonhmi_pmem_PowerSave_clearall
        (JNIEnv *env, jobject thiz);

    
    JNIEXPORT void JNICALL Java_com_android_Samkoonhmi_pmem_PowerSave_write
        (JNIEnv *env, jobject thiz,jobject joComParam);    
        
JNIEXPORT void JNICALL Java_com_android_Samkoonhmi_pmem_PowerSave_read
        (JNIEnv *env, jobject thiz,jobject joComParam,jbyteArray out);

#ifdef __cplusplus
}
#endif
#endif
