package com.android.Samkoonhmi.skenum;

public enum SYSTEM_OPER_TYPE {
	SYSTEM_BACKLIGHT_OFF,
	SYSTEM_BACKLIGHT_ON,
	SYSTEM_RESET,
	SYSTEM_SET_SCENE_TIME,
	SYSTEM_SET_DATE,
	SYSTEM_SET_TIME,
	SYSTEM_SET_SOUND_ON,
	SYSTEM_SET_SOUND_OFF,
	SYSTEM_CHANGE_LANGUAGE,
	SYSTEM_LOCK,
	SYSTEM_UNLOCK,
	SYSTEM_TATOL_OPER
}
