/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_winplus_serial_utils_SerialPort */

#ifndef _Included_SerialPort_H
#define _Included_SerialPort_H

typedef struct comPortParamProp
{
    /*串口的编号*/
    int nSerialPortNum;

    /*波特率*/
    int nBaudRate;

    /*数据位*/
    int nDataBits;

    /*检验方式*/
    int nParityType;

    /*停止位*/
    int nStopBit;

    /*数据流控制方式*/
    int nFlowType;

}COM_PORT_PARAM_PROP;

COM_PORT_PARAM_PROP getComParamFromJni(JNIEnv *env, jobject joComParam);



#ifdef __cplusplus
extern "C" {
#endif
    /*
 * Class:     org_winplus_serial_utils_SerialPort
 * Method:    open
 * Signature: (Ljava/lang/String;II)Ljava/io/FileDescriptor;
 */
    JNIEXPORT jobject JNICALL Java_com_android_Samkoonhmi_serial_SerialPort_open
            (JNIEnv *, jclass, jobject, jint);

    /*
 * Class:     org_winplus_serial_utils_SerialPort
 * Method:    close
 * Signature: ()V
 */
    JNIEXPORT void JNICALL Java_com_android_Samkoonhmi_serial_SerialPort_close
            (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
