/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "stdafx.h"
#ifndef _Included_Skcommon_H
#define _Included_Skcommon_H

typedef struct sk_common_info_t{
	int module;
	int TMP1;
	int TMP2;
} SK_COMMON_INFO_T;

SK_COMMON_INFO_T getSkCommonParamFromJni(JNIEnv *env, jobject joSkCommonParam);
void setSkCommonParamToJni(JNIEnv *env, jobject joSend, SK_COMMON_INFO_T mSk_common_info_t);

#ifdef __cplusplus
extern "C" {
#endif
JNIEXPORT void JNICALL Java_com_android_Samkoonhmi_skcommon_SkCommon_open
        (JNIEnv *env, jobject thiz);

JNIEXPORT void JNICALL Java_com_android_Samkoonhmi_skcommon_SkCommon_close
        (JNIEnv *env, jobject thiz);        

JNIEXPORT void JNICALL Java_com_android_Samkoonhmi_skcommon_SkCommon_backlighton
        (JNIEnv *env, jobject thiz);

JNIEXPORT void JNICALL Java_com_android_Samkoonhmi_skcommon_SkCommon_backlightoff
        (JNIEnv *env, jobject thiz);

JNIEXPORT void JNICALL Java_com_android_Samkoonhmi_skcommon_SkCommon_getmode0
        (JNIEnv *env, jobject thiz,jobject joComParam);
        
JNIEXPORT void JNICALL Java_com_android_Samkoonhmi_skcommon_SkCommon_getmode1
        (JNIEnv *env, jobject thiz,jobject joComParam);

JNIEXPORT void JNICALL Java_com_android_Samkoonhmi_skcommon_SkCommon_getmode2
        (JNIEnv *env, jobject thiz,jobject joComParam);
                        
#ifdef __cplusplus
}
#endif
#endif
